[package]
name = "rolling-hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
blake2 = "0.9.2"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
